version: '3.8'

services:
  willuemailme:
    build: .
    ports:
      - "80:80"
    environment:
      - HOST_DOMAIN=${HOST_DOMAIN}
      - CLIENT_KEY=${CLIENT_KEY}
      - RECIPIENT_ADDRESS=${RECIPIENT_ADDRESS}
      - RECIPIENT_PASSWORD=${RECIPIENT_PASSWORD}
      - PORT=80
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:80/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
